### ISSUE TITLE
Bug in Reply Modal window 🐛 

### ISSUE THREAD

**Issue by yogeshdecodes** [tarunsinghdev/bird-app#24]
Clicking anywhere on reply modal window opens respective tweet page.

### Reason
It's because of Event bubbling which is a method of event propagation in the HTML DOM API when an event is in an element inside another element, and both elements have registered a handle to that event. In event bubbling, the event is first captured and handled by the innermost element and then propagated to outer elements.

### Solution
I tried stopPropagation() method to prevents further propagation of the current event.

**Comment by tarunsinghdev** [comment]
Thanks for pointing out.
